name: Reproduce Chrome Hang with DynamoRIO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reproduce-hang:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Google Chrome
      - name: Install Google Chrome
        run: |
          choco install googlechrome --no-progress

      # Step 3: Set up DynamoRIO
      - name: Download and install DynamoRIO
        working-directory: ${{ github.workspace }}
        run: |
        
          curl -LO https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.93.19979/DynamoRIO-Windows-10.93.19979.zip
          tar -xvzf DynamoRIO-Windows-10.93.19979.zip
          dir

      # Step 4: Run Chrome under DynamoRIO with the -persist option
      - name: Run Chrome with DynamoRIO
        working-directory: ${{ github.workspace }}
        run: |
          # Navigate to DynamoRIO bin directory
          # cd D:/a/dynamorio-test/dynamorio-test/

          # Use DynamoRIO to run chrome.exe with -persist
          ./D:/a/dynamorio-test/dynamorio-test/DynamoRIO-Windows-10.93.19979/bin/drrun.exe -- "C:\Program Files\Google\Chrome\Application\chrome.exe" "D:\a\dynamorio-test\dynamorio-test\close.html"
          
      # Step 5: Monitor for the hang issue
      - name: Check for hang or errors
        run: |
          # Check if Chrome is still running or if there was a hang
          tasklist | findstr chrome
